#################################################
# Playbooks: Kubernetes Install
#################################################
---
- hosts: control
  remote_user: vagrant
  become: true
  tasks:
    - name: Initialize the Kubernetes cluster using kubeadm
      command: kubeadm init --apiserver-advertise-address="192.168.56.4" --apiserver-cert-extra-sans="192.168.56.4" --node-name k8s-master --pod-network-cidr=192.168.0.0/16

    - name: Create .kube directory
      file:
        path: /home/vagrant/.kube
        state: directory
        mode: 0755

    - name: Setup kubeconfig for vagrant user
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/vagrant/.kube/config
        remote_src: yes
        owner: vagrant

    - name: Get the token for joining the worker nodes
      shell: kubeadm token create  --print-join-command
      register: kubernetes_join_command

    - debug:
        msg: "{{ kubernetes_join_command.stdout }}"

    - name: Copy join command to local file.
      shell: echo {{ kubernetes_join_command.stdout_lines[0] }} >> /vagrant/kubernetes_join_command
